# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Express App CICD

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: self-hosted

        strategy:
            matrix:
                node-version: [10.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: "Intalling Packages"
              run: npm install
            - name: "Build Code"
              run: npm run build
            - name: create env file
              run: |
                touch .env
                echo NODE_ENV=production >> .env
                echo PORT=3000 >> .env
            - name: "Run Pm2"
              env: 
                PORT: 3000
              run: pm2 restart express-app
